server:
  port: 9001 #服务端口
#mybatis配置
type-aliases-package: com.lidadaibiao.pojo   #扫描包
  mapper-locations: classpath:mybatis/mapper/*.xml #扫描mapper文件的地址
  config-location: classpath:mybatis/mybatis-config.xml #扫描加载config文件
#spring配置
spring:
  application:
    name: SpringCloud-Provider-Dept  #服务名
  datasource: #数据库相关配置
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/cloudtest1?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root